# Generated by Django 5.2.5 on 2025-08-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
            ],
        ),
    ]
