# Generated by Django 5.2.5 on 2025-08-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Titre',
            field=models.CharField(max_length=200),
        ),
    ]
