# Generated by Django 5.2.5 on 2025-08-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0002_alter_tasks_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='contenu',
        ),
        migrations.AddField(
            model_name='tasks',
            name='est_complet',
            field=models.BooleanField(default=False),
        ),
    ]
