# Generated by Django 5.2.5 on 2025-08-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0003_remove_tasks_contenu_tasks_est_complet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='est_complet',
        ),
    ]
