# Generated by Django 5.2.5 on 2025-08-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0004_remove_tasks_est_complet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='est_valide',
        ),
    ]
