# Generated by Django 5.2.5 on 2025-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0005_remove_tasks_date_remove_tasks_est_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Titre',
            field=models.CharField(max_length=255),
        ),
    ]
