# Generated by Django 5.2.5 on 2025-08-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0006_alter_tasks_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='Titre',
            new_name='titre',
        ),
    ]
