# Generated by Django 5.2.5 on 2025-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0007_rename_titre_tasks_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
