# Generated by Django 5.2.5 on 2025-08-18 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0008_tasks_statut_alter_tasks_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tasks',
            name='heure',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
