# Generated by Django 5.2.5 on 2025-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0009_tasks_date_tasks_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
