# Generated by Django 5.2.5 on 2025-09-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionneur_task', '0010_tasks_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='heure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
